# Generated by Django 6.1 on 2026-09-11 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoommateChatSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('basic5', '5 Chats - ₹9')], default='basic5', max_length=20)),
                ('amount', models.PositiveIntegerField(default=9)),
                ('chats_limit', models.PositiveIntegerField(default=5)),
                ('chats_used', models.PositiveIntegerField(default=0)),
                ('cf_order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('cf_payment_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('failed', 'Failed')], default='created', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_chat_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoommateReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('fake_profile', 'Fake Profile'), ('harassment', 'Harassment'), ('inappropriate', 'Inappropriate Content'), ('spam', 'Spam'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewing', 'Reviewing'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_reports_against', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filed_roommate_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoommateBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_blocks_received', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_blocks_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('blocker', 'blocked'), name='unique_roommate_block')],
            },
        ),
        migrations.CreateModel(
            name='RoommateConnectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_roommate_requests', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_roommate_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('sender', 'receiver'), name='unique_pending_roommate_request')],
            },
        ),
        migrations.CreateModel(
            name='RoommateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='roommates/profile_photos/')),
                ('full_name', models.CharField(max_length=150)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20)),
                ('college', models.CharField(max_length=200)),
                ('course', models.CharField(blank=True, max_length=150)),
                ('preferred_location', models.CharField(max_length=150)),
                ('budget_min', models.PositiveIntegerField()),
                ('budget_max', models.PositiveIntegerField()),
                ('accommodation_type', models.CharField(choices=[('room', 'Room'), ('pg', 'PG'), ('flat', 'Flat')], max_length=10)),
                ('sharing_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple')], max_length=10)),
                ('move_in_date', models.DateField()),
                ('food_preference', models.CharField(choices=[('veg', 'Veg'), ('non_veg', 'Non-Veg'), ('both', 'Both')], max_length=10)),
                ('smoking', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('drinking', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('sleep_schedule', models.CharField(choices=[('early_sleeper', 'Early Sleeper'), ('flexible', 'Flexible'), ('night_owl', 'Night Owl')], max_length=20)),
                ('cleanliness', models.CharField(choices=[('very_clean', 'Very Clean'), ('moderate', 'Moderate'), ('flexible', 'Flexible')], max_length=15)),
                ('study_habits', models.CharField(choices=[('quiet', 'Quiet'), ('sometimes_music', 'Sometimes Music'), ('social', 'Social')], max_length=20)),
                ('interests', models.CharField(blank=True, help_text='Comma-separated, e.g. Music, Football, Reading', max_length=300)),
                ('bio', models.TextField(blank=True, max_length=800)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide profile from search')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='roommates_r_is_acti_ca38cb_idx'), models.Index(fields=['preferred_location'], name='roommates_r_preferr_3f1efc_idx'), models.Index(fields=['college'], name='roommates_r_college_2ddde2_idx')],
            },
        ),
    ]
