# Generated by Django 6.1 on 2026-09-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommateprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text="10-digit mobile number. Only shown to users who've unlocked chat credits.", max_length=10),
        ),
    ]
