# Generated by Django 6.1 on 2026-09-14 09:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0002_roommateprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommateprofile',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
