# Generated by Django 6.1 on 2026-08-11 04:29

import django.db.models.deletion
import leads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(default=leads.models.generate_lead_id, editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=150, verbose_name='Naam')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('city', models.CharField(default='Kanpur', max_length=100, verbose_name='Shehar')),
                ('budget', models.CharField(default='2000', max_length=30, verbose_name='Budget (₹)')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('status', models.CharField(choices=[('active', 'Active'), ('booked', 'Booked'), ('lost', 'Lost')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_created', to='leads.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('booked', 'Booked'), ('lost', 'Lost')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.employee')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='leads.lead')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
