# Generated by Django 6.1 on 2026-08-12 08:41

import django.db.models.deletion
import django.utils.timezone
import leads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(default=leads.models.generate_customer_lead_id, editable=False, max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=150, verbose_name='Customer Naam')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('requirement', models.CharField(blank=True, max_length=255, verbose_name='Requirement')),
                ('contacted', models.BooleanField(default=False)),
                ('next_followup', models.DateField(blank=True, null=True, verbose_name='Next Follow-up')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.CharField(default=leads.models.generate_partner_listing_id, editable=False, max_length=20, unique=True)),
                ('partner_name', models.CharField(max_length=150, verbose_name='Partner Naam')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='Location')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('contacted', models.BooleanField(default=False)),
                ('next_followup', models.DateField(blank=True, null=True, verbose_name='Next Follow-up')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerContactLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacted_date', models.DateField(default=django.utils.timezone.localdate)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('contacted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.employee')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_logs', to='leads.customerlead')),
            ],
            options={
                'ordering': ['-contacted_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PartnerContactLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacted_date', models.DateField(default=django.utils.timezone.localdate)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('contacted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.employee')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_logs', to='leads.partnerlead')),
            ],
            options={
                'ordering': ['-contacted_date', '-id'],
            },
        ),
    ]
