# Generated by Django 6.1 on 2026-08-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_customerlead_partnerlead_customercontactlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerlead',
            name='listing_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='Listing ID'),
        ),
    ]
