# Generated by Django 6.0 on 2026-04-11 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_remove_booking_user_remove_roombooking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_bookings', to='listings.listings'),
        ),
    ]
