# Generated by Django 6.0 on 2026-04-12 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_roombooking_room'),
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.partner'),
        ),
    ]
