# Generated by Django 6.0 on 2026-04-12 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_listings_partner'),
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='partner.partner'),
        ),
    ]
