# Generated by Django 6.0 on 2026-04-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_roombooking_partner_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='listings',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='listings',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='status',
            field=models.CharField(choices=[('pending_verification', 'Pending Verification'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending_verification', max_length=30),
        ),
    ]
