# Generated by Django 6.0 on 2026-04-16 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_listings_latitude_listings_location_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('commission_amount', models.IntegerField(default=0)),
                ('landlord_amount', models.IntegerField(default=0)),
                ('transfer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.CharField(default='created', max_length=30)),
                ('transfer_status', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='listings.roombooking')),
            ],
        ),
    ]
