# Generated by Django 6.0.2 on 2026-06-06 04:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_alter_listings_room_images1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='Room_images1',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='Room_images2',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
