# Generated by Django 6.0.2 on 2026-06-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_alter_listings_room_images1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='verified_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
