# Generated by Django 6.0.2 on 2026-06-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_roombooking_is_verified_roombooking_verified_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
    ]
