# Generated by Django 6.0.2 on 2026-06-24 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_roomrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomrating',
            name='name',
        ),
    ]
