# Generated by Django 6.0.2 on 2026-07-03 05:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='Room_video1',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='video'),
        ),
        migrations.AddField(
            model_name='listings',
            name='Room_video2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
        migrations.AddField(
            model_name='listings',
            name='Room_video3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
        migrations.AddField(
            model_name='listings',
            name='Room_video4',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
    ]
