# Generated by Django 6.0.2 on 2026-07-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_listings_room_video1_listings_room_video2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='bathroom_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listings',
            name='bathroom_type',
            field=models.CharField(choices=[('none', 'No Bathroom'), ('attached', 'Attached'), ('shared', 'Shared')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='listings',
            name='hall_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listings',
            name='has_dining_hall',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listings',
            name='has_hall',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listings',
            name='kitchen_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listings',
            name='kitchen_type',
            field=models.CharField(choices=[('none', 'No Kitchen'), ('private', 'Private'), ('shared', 'Shared')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='listings',
            name='room_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
