# Generated by Django 6.0.2 on 2026-08-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0029_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
