# Generated by Django 5.2.15 on 2026-08-08 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0030_participant_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('basic', 'Basic - 20 Chats (14 days)'), ('unlimited', 'Unlimited Chats (14 days)')], max_length=20)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('cf_order_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('cf_payment_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('active', 'Active'), ('failed', 'Failed'), ('expired', 'Expired')], default='created', max_length=20)),
                ('chats_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('chats_used', models.PositiveIntegerField(default=0)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_subscriptions', to='listings.listings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]