# Generated by Django 6.1 on 2026-08-25 08:21

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0033_roomlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='RakhiRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('college', models.CharField(blank=True, max_length=200)),
                ('contact', models.CharField(blank=True, help_text='Phone ya Email', max_length=100)),
                ('instagram_handle', models.CharField(blank=True, max_length=100)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='RakhiSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('college', models.CharField(blank=True, max_length=200)),
                ('instagram_handle', models.CharField(blank=True, max_length=100)),
                ('gemini_prompt', models.TextField(help_text='Exact Gemini prompt used')),
                ('room_summary', models.TextField(help_text='Perfect room design summary')),
                ('rakhi_concept', models.TextField(help_text='Rakhi surprise concept')),
                ('output_type', models.CharField(choices=[('poster', 'Poster'), ('reel', '30-sec Reel'), ('image', 'Room / Rakhi Image Concept'), ('mini_ad', 'Mini Advertisement')], max_length=20)),
                ('output_file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='output_file')),
                ('output_link', models.URLField(blank=True, max_length=500)),
                ('proof_screenshot', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='proof_screenshot')),
                ('proof_link', models.URLField(blank=True, help_text='Instagram story highlight / WhatsApp status link, agar abhi bhi live hai', max_length=500)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
