# Generated by Django 6.0.2 on 2026-06-25 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
