# Generated by Django 6.0.2 on 2026-08-04 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
