# Generated by Django 6.0 on 2026-04-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_fcmtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='razorpay_account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
