# Generated by Django 6.0.2 on 2026-06-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_fcmtoken_partner_fcmtoken_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
