# Generated by Django 6.1 on 2026-09-18 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0035_blacklistedroom'),
        ('partner', '0005_partner_upi_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount_percent', models.PositiveIntegerField(default=0, help_text='e.g. 20 for 20% off. Leave 0 if using a flat amount instead.')),
                ('discount_amount', models.PositiveIntegerField(default=0, help_text='Flat rupee discount. Leave 0 if using a percentage instead.')),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 = unlimited uses')),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_till', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cf_order_id', models.CharField(help_text='Our own order_id, sent to Cashfree', max_length=100, unique=True)),
                ('base_amount', models.PositiveIntegerField(default=49)),
                ('discount_amount', models.PositiveIntegerField(default=0)),
                ('final_amount', models.PositiveIntegerField(default=49)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('failed', 'Failed')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner.coupon')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.listings')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.partner')),
            ],
        ),
    ]
